/*------------------------------------------------------------------------------
 * This code was generated by Spiral Multiplier Block Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */

module MCM_1 (
        X,
        Y1,
        Y2,
        Y3,
        Y4,
        Y5,
        Y6,
        Y7,
        Y8,
        Y9,
        Y10,
        Y11,
        Y12,
        Y13,
        Y14,
        Y15
);

        // Port mode declarations:
        input  unsigned  [7:0] X;
        output signed  [15:0]
                Y1,
                Y2,
                Y3,
                Y4,
                Y5,
                Y6,
                Y7,
                Y8,
                Y9,
                Y10,
                Y11,
                Y12,
                Y13,
                Y14,
                Y15;

        wire [15:0] Y [0:15];

        assign Y1 = Y[0];
        assign Y2 = Y[1];
        assign Y3 = Y[2];
        assign Y4 = Y[3];
        assign Y5 = Y[4];
        assign Y6 = Y[5];
        assign Y7 = Y[6];
        assign Y8 = Y[7];
        assign Y9 = Y[8];
        assign Y10 = Y[9];
        assign Y11 = Y[10];
        assign Y12 = Y[11];
        assign Y13 = Y[12];
        assign Y14 = Y[13];
        assign Y15 = Y[14];

        //Multipliers:

        wire signed [15:0]
                w1,
                w2,
                w3,
                w4,
                w5,
                w6,
                w7,
                w8,
                w9,
                w10,
                w11,
                w12,
                w13,
                w14,
                w15,
                w16,
                w17,
                w18,
                w19,
                w20,
                w21,
                w22,
                w23,
                w24,
                w25,
                w26,
                w27,
                w28,
                w29;

        assign w1 = X;
        assign w2 = w1 << 2; // w2 = 4x
        assign w3 = w2 - w1; // w3 = 3x
        assign w4 = w1 + w2; // w4 = 5x
        assign w5 = w1 << 3; // w5 = 8x
        assign w6 = w5 - w1; // w6 = 7x
        assign w7 = w1 + w5; // w7 = 9x
        assign w8 = w1 << 4; // w8 = 16x
        assign w9 = w8 - w1; // w9 = 15x
        assign w10 = w3 + w5; // w10 = 11x
        assign w11 = w8 - w3; // w11 = 13x
        assign w12 = w1 << 5; // w12 = 32x
        assign w13 = w12 - w4; // w13 = 27x
        assign w14 = w3 << 4; // w14 = 48x
        assign w15 = w14 - w1; // w15 = 47x
        assign w16 = w1 << 6; // w16 = 64x
        assign w17 = w16 - w4; // w17 = 59x
        assign w18 = w1 << 1; // w18 = 2x
        assign w19 = -1 * w18; // w19 = -2x
        assign w20 = -1 * w4; // w20 = -5x
        assign w21 = -1 * w3; // w21 = -3x
        assign w22 = -1 * w1; // w22 = -1x
        assign w23 = w6 << 1; // w23 = 14x
        assign w24 = w4 << 1; // w24 = 10x
        assign w25 = w3 << 1; // w25 = 6x
        assign w26 = w9 << 1; // w26 = 30x
        assign w27 = w11 << 1; // w27 = 26x
        assign w28 = w10 << 1; // w28 = 22x
        assign w29 = w7 << 1; // w29 = 18x

        assign Y[0] = w19;
        assign Y[1] = w20;
        assign Y[2] = w21;
        assign Y[3] = w22;
        assign Y[4] = w23;
        assign Y[5] = w24;
        assign Y[6] = w25;
        assign Y[7] = w18;
        assign Y[8] = w17;
        assign Y[9] = w15;
        assign Y[10] = w13;
        assign Y[11] = w26;
        assign Y[12] = w27;
        assign Y[13] = w28;
        assign Y[14] = w29;

endmodule //MCM_1

