/*------------------------------------------------------------------------------
 * This code was generated by Spiral Multiplier Block Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */

module MCM_4 (
        X,
        Y1,
        Y2,
        Y3,
        Y4,
        Y5,
        Y6,
        Y7,
        Y8,
        Y9,
        Y10,
        Y11,
        Y12,
        Y13,
        Y14,
        Y15,
        Y16,
        Y17,
        Y18,
        Y19,
        Y20,
        Y21,
        Y22,
        Y23,
        Y24
);

        // Port mode declarations:
        input  unsigned  [7:0] X;
        output signed  [15:0]
                Y1,
                Y2,
                Y3,
                Y4,
                Y5,
                Y6,
                Y7,
                Y8,
                Y9,
                Y10,
                Y11,
                Y12,
                Y13,
                Y14,
                Y15,
                Y16,
                Y17,
                Y18,
                Y19,
                Y20,
                Y21,
                Y22,
                Y23,
                Y24;

        wire [15:0] Y [0:24];

        assign Y1 = Y[0];
        assign Y2 = Y[1];
        assign Y3 = Y[2];
        assign Y4 = Y[3];
        assign Y5 = Y[4];
        assign Y6 = Y[5];
        assign Y7 = Y[6];
        assign Y8 = Y[7];
        assign Y9 = Y[8];
        assign Y10 = Y[9];
        assign Y11 = Y[10];
        assign Y12 = Y[11];
        assign Y13 = Y[12];
        assign Y14 = Y[13];
        assign Y15 = Y[14];
        assign Y16 = Y[15];
        assign Y17 = Y[16];
        assign Y18 = Y[17];
        assign Y19 = Y[18];
        assign Y20 = Y[19];
        assign Y21 = Y[20];
        assign Y22 = Y[21];
        assign Y23 = Y[22];
        assign Y24 = Y[23];

        //Multipliers:

        wire signed [15:0]
                w1,
                w2,
                w3,
                w4,
                w5,
                w6,
                w7,
                w8,
                w9,
                w10,
                w11,
                w12,
                w13,
                w14,
                w15,
                w16,
                w17,
                w18,
                w19,
                w20,
                w21,
                w22,
                w23,
                w24,
                w25,
                w26,
                w27,
                w28,
                w29,
                w30,
                w31,
                w32,
                w33,
                w34;

        assign w1 = X;
        assign w2 = w1 << 2; // w2 = 4x
        assign w3 = w2 - w1; // w3 = 3x
        assign w4 = w1 + w2; // w4 = 5x
        assign w5 = w1 << 3; // w5 = 8x
        assign w6 = w1 + w5; // w6 = 9x
        assign w7 = w1 << 4; // w7 = 16x
        assign w8 = w7 - w1; // w8 = 15x
        assign w9 = w1 + w7; // w9 = 17x
        assign w10 = w3 + w5; // w10 = 11x
        assign w11 = w7 - w3; // w11 = 13x
        assign w12 = w4 + w7; // w12 = 21x
        assign w13 = w3 << 3; // w13 = 24x
        assign w14 = w1 + w13; // w14 = 25x
        assign w15 = w1 << 5; // w15 = 32x
        assign w16 = w15 - w4; // w16 = 27x
        assign w17 = w15 - w3; // w17 = 29x
        assign w18 = w3 << 4; // w18 = 48x
        assign w19 = w18 - w3; // w19 = 45x
        assign w20 = w18 - w1; // w20 = 47x
        assign w21 = w1 << 6; // w21 = 64x
        assign w22 = w21 - w4; // w22 = 59x
        assign w23 = w4 << 1; // w23 = 10x
        assign w24 = w8 << 1; // w24 = 30x
        assign w25 = w11 << 1; // w25 = 26x
        assign w26 = w10 << 1; // w26 = 22x
        assign w27 = w6 << 1; // w27 = 18x
        assign w28 = w17 << 1; // w28 = 58x
        assign w29 = -1 * w1; // w29 = -1x
        assign w30 = -1 * w3; // w30 = -3x
        assign w31 = -1 * w4; // w31 = -5x
        assign w32 = w1 << 1; // w32 = 2x
        assign w33 = -1 * w32; // w33 = -2x
        assign w34 = w1; // w34 = 1x

        assign Y[0] = w22;
        assign Y[1] = w20;
        assign Y[2] = w16;
        assign Y[3] = w23;
        assign Y[4] = w24;
        assign Y[5] = w25;
        assign Y[6] = w26;
        assign Y[7] = w27;
        assign Y[8] = w5;
        assign Y[9] = w13;
        assign Y[10] = w19;
        assign Y[11] = w28;
        assign Y[12] = w9;
        assign Y[13] = w12;
        assign Y[14] = w14;
        assign Y[15] = w17;
        assign Y[16] = w29;
        assign Y[17] = w30;
        assign Y[18] = w31;
        assign Y[19] = w33;
        assign Y[20] = w34;
        assign Y[21] = w4;
        assign Y[22] = w6;
        assign Y[23] = w11;

endmodule //MCM_4

