/*------------------------------------------------------------------------------
 * This code was generated by Spiral Multiplier Block Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */

module multiplier_block (
    X,
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8
);

  // Port mode declarations:
  input  signed  [31:0] X;
  output signed  [31:0]
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8;

  wire [31:0] Y [0:7];

  assign Y1 = Y[0];
  assign Y2 = Y[1];
  assign Y3 = Y[2];
  assign Y4 = Y[3];
  assign Y5 = Y[4];
  assign Y6 = Y[5];
  assign Y7 = Y[6];
  assign Y8 = Y[7];

  //Multipliers:

  wire signed [32:0]
    w1,
    w4,
    w5,
    w8,
    w9,
    w16,
    w15,
    w11,
    w13,
    w32,
    w27,
    w47,
    w64,
    w59,
    w118,
    w20,
    w94,
    w36,
    w44,
    w52,
    w54,
    w60;

  assign w1 = X;
  assign w4 = w1 << 2;
  assign w5 = w1 + w4;
  assign w8 = w1 << 3;
  assign w9 = w1 + w8;
  assign w16 = w1 << 4;
  assign w15 = w16 - w1;
  assign w11 = w16 - w5;
  assign w13 = w5 + w8;
  assign w32 = w1 << 5;
  assign w27 = w32 - w5;
  assign w47 = w15 + w32;
  assign w64 = w1 << 6;
  assign w59 = w64 - w5;
  assign w118 = w59 << 1;
  assign w20 = w5 << 2;
  assign w94 = w47 << 1;
  assign w36 = w9 << 2;
  assign w44 = w11 << 2;
  assign w52 = w13 << 2;
  assign w54 = w27 << 1;
  assign w60 = w15 << 2;

  assign Y[0] = w118[32:1];
  assign Y[1] = w20[32:1];
  assign Y[2] = w94[32:1];
  assign Y[3] = w36[32:1];
  assign Y[4] = w44[32:1];
  assign Y[5] = w52[32:1];
  assign Y[6] = w54[32:1];
  assign Y[7] = w60[32:1];

endmodule //multiplier_block

