/*------------------------------------------------------------------------------
 * This code was generated by Spiral Multiplier Block Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */

module multiplier_block (
    X,
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8
);

  // Port mode declarations:
  input  signed  [31:0] X;
  output signed  [31:0]
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8;

  wire [31:0] Y [0:7];

  assign Y1 = Y[0];
  assign Y2 = Y[1];
  assign Y3 = Y[2];
  assign Y4 = Y[3];
  assign Y5 = Y[4];
  assign Y6 = Y[5];
  assign Y7 = Y[6];
  assign Y8 = Y[7];

  //Multipliers:

  wire signed [32:0]
    w1,
    w4,
    w3,
    w16,
    w17,
    w21,
    w24,
    w25,
    w32,
    w29,
    w48,
    w45,
    w90,
    w34,
    w42,
    w50,
    w116,
    w58;

  assign w1 = X;
  assign w4 = w1 << 2;
  assign w3 = w4 - w1;
  assign w16 = w1 << 4;
  assign w17 = w1 + w16;
  assign w21 = w17 + w4;
  assign w24 = w3 << 3;
  assign w25 = w1 + w24;
  assign w32 = w1 << 5;
  assign w29 = w32 - w3;
  assign w48 = w3 << 4;
  assign w45 = w48 - w3;
  assign w90 = w45 << 1;
  assign w34 = w17 << 1;
  assign w42 = w21 << 1;
  assign w50 = w25 << 1;
  assign w116 = w29 << 2;
  assign w58 = w29 << 1;

  assign Y[0] = w16[32:1];
  assign Y[1] = w90[32:1];
  assign Y[2] = w34[32:1];
  assign Y[3] = w42[32:1];
  assign Y[4] = w48[32:1];
  assign Y[5] = w50[32:1];
  assign Y[6] = w116[32:1];
  assign Y[7] = w58[32:1];

endmodule //multiplier_block

