/*------------------------------------------------------------------------------
 * This code was generated by Spiral Multiplier Block Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */

module MCM_1 (
        X,
        Y1,
        Y2,
        Y3,
        Y4,
        Y5,
        Y6,
        Y7,
        Y8
);

        // Port mode declarations:
        input  unsigned  [7:0] X;
        output signed  [15:0]
                Y1,
                Y2,
                Y3,
                Y4,
                Y5,
                Y6,
                Y7,
                Y8;

        wire [15:0] Y [0:7];

        assign Y1 = Y[0];
        assign Y2 = Y[1];
        assign Y3 = Y[2];
        assign Y4 = Y[3];
        assign Y5 = Y[4];
        assign Y6 = Y[5];
        assign Y7 = Y[6];
        assign Y8 = Y[7];

        //Multipliers:

        wire signed [15:0]
                w1,
                w2,
                w3,
                w4,
                w5,
                w6,
                w7,
                w8,
                w9,
                w10,
                w11,
                w12,
                w13,
                w14,
                w15,
                w16,
                w17,
                w18,
                w19;

        assign w1 = X;
        assign w2 = w1 << 2; // w2 = 4x
        assign w3 = w1 + w2; // w3 = 5x
        assign w4 = w1 << 3; // w4 = 8x
        assign w5 = w1 + w4; // w5 = 9x
        assign w6 = w1 << 4; // w6 = 16x
        assign w7 = w6 - w1; // w7 = 15x
        assign w8 = w6 - w3; // w8 = 11x
        assign w9 = w3 + w4; // w9 = 13x
        assign w10 = w1 << 5; // w10 = 32x
        assign w11 = w10 - w3; // w11 = 27x
        assign w12 = w7 + w10; // w12 = 47x
        assign w13 = w1 << 6; // w13 = 64x
        assign w14 = w13 - w3; // w14 = 59x
        assign w15 = w3 << 1; // w15 = 10x
        assign w16 = w7 << 1; // w16 = 30x
        assign w17 = w9 << 1; // w17 = 26x
        assign w18 = w8 << 1; // w18 = 22x
        assign w19 = w5 << 1; // w19 = 18x

        assign Y[0] = w14;
        assign Y[1] = w12;
        assign Y[2] = w11;
        assign Y[3] = w15;
        assign Y[4] = w16;
        assign Y[5] = w17;
        assign Y[6] = w18;
        assign Y[7] = w19;

endmodule //MCM_1

