/*------------------------------------------------------------------------------
 * This code was generated by Spiral Multiplier Block Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */

module MCM_2 (
        X,
        Y1,
        Y2,
        Y3,
        Y4,
        Y5,
        Y6,
        Y7,
        Y8,
        Y9,
        Y10,
        Y11,
        Y12,
        Y13,
        Y14,
        Y15,
        Y16,
        Y17,
        Y18,
        Y19,
        Y20,
        Y21,
        Y22,
        Y23
);

        // Port mode declarations:
        input  unsigned  [7:0] X;
        output signed  [15:0]
                Y1,
                Y2,
                Y3,
                Y4,
                Y5,
                Y6,
                Y7,
                Y8,
                Y9,
                Y10,
                Y11,
                Y12,
                Y13,
                Y14,
                Y15,
                Y16,
                Y17,
                Y18,
                Y19,
                Y20,
                Y21,
                Y22,
                Y23;

        wire [15:0] Y [0:23];

        assign Y1 = Y[0];
        assign Y2 = Y[1];
        assign Y3 = Y[2];
        assign Y4 = Y[3];
        assign Y5 = Y[4];
        assign Y6 = Y[5];
        assign Y7 = Y[6];
        assign Y8 = Y[7];
        assign Y9 = Y[8];
        assign Y10 = Y[9];
        assign Y11 = Y[10];
        assign Y12 = Y[11];
        assign Y13 = Y[12];
        assign Y14 = Y[13];
        assign Y15 = Y[14];
        assign Y16 = Y[15];
        assign Y17 = Y[16];
        assign Y18 = Y[17];
        assign Y19 = Y[18];
        assign Y20 = Y[19];
        assign Y21 = Y[20];
        assign Y22 = Y[21];
        assign Y23 = Y[22];

        //Multipliers:

        wire signed [15:0]
                w1,
                w2,
                w3,
                w4,
                w5,
                w6,
                w7,
                w8,
                w9,
                w10,
                w11,
                w12,
                w13,
                w14,
                w15,
                w16,
                w17,
                w18,
                w19,
                w20,
                w21,
                w22,
                w23,
                w24,
                w25,
                w26,
                w27,
                w28,
                w29,
                w30,
                w31,
                w32,
                w33,
                w34,
                w35,
                w36;

        assign w1 = X;
        assign w2 = w1 << 2; // w2 = 4x
        assign w3 = w2 - w1; // w3 = 3x
        assign w4 = w1 + w2; // w4 = 5x
        assign w5 = w1 << 3; // w5 = 8x
        assign w6 = w5 - w1; // w6 = 7x
        assign w7 = w1 + w5; // w7 = 9x
        assign w8 = w1 << 4; // w8 = 16x
        assign w9 = w8 - w1; // w9 = 15x
        assign w10 = w1 + w8; // w10 = 17x
        assign w11 = w3 + w5; // w11 = 11x
        assign w12 = w8 - w3; // w12 = 13x
        assign w13 = w4 + w8; // w13 = 21x
        assign w14 = w3 << 3; // w14 = 24x
        assign w15 = w1 + w14; // w15 = 25x
        assign w16 = w1 << 5; // w16 = 32x
        assign w17 = w16 - w4; // w17 = 27x
        assign w18 = w16 - w3; // w18 = 29x
        assign w19 = w3 << 4; // w19 = 48x
        assign w20 = w19 - w3; // w20 = 45x
        assign w21 = w19 - w1; // w21 = 47x
        assign w22 = w1 << 6; // w22 = 64x
        assign w23 = w22 - w4; // w23 = 59x
        assign w24 = w1 << 1; // w24 = 2x
        assign w25 = -1 * w24; // w25 = -2x
        assign w26 = -1 * w4; // w26 = -5x
        assign w27 = -1 * w3; // w27 = -3x
        assign w28 = -1 * w1; // w28 = -1x
        assign w29 = w6 << 1; // w29 = 14x
        assign w30 = w4 << 1; // w30 = 10x
        assign w31 = w3 << 1; // w31 = 6x
        assign w32 = w9 << 1; // w32 = 30x
        assign w33 = w12 << 1; // w33 = 26x
        assign w34 = w11 << 1; // w34 = 22x
        assign w35 = w7 << 1; // w35 = 18x
        assign w36 = w18 << 1; // w36 = 58x

        assign Y[0] = w25;
        assign Y[1] = w26;
        assign Y[2] = w27;
        assign Y[3] = w28;
        assign Y[4] = w29;
        assign Y[5] = w30;
        assign Y[6] = w31;
        assign Y[7] = w24;
        assign Y[8] = w23;
        assign Y[9] = w21;
        assign Y[10] = w17;
        assign Y[11] = w32;
        assign Y[12] = w33;
        assign Y[13] = w34;
        assign Y[14] = w35;
        assign Y[15] = w5;
        assign Y[16] = w14;
        assign Y[17] = w20;
        assign Y[18] = w36;
        assign Y[19] = w10;
        assign Y[20] = w13;
        assign Y[21] = w15;
        assign Y[22] = w18;

endmodule //MCM_2

